export const API_CONFIG = {
  baseUrl: 'https://fastapidev.createdsarl.com/v1',
  endpoints: {
    login: '/auth/admins',
    refreshToken: '/auth/refresh',
    loadAllDepartures: '/loadalldep',
    loadGareDest: '/loadgaredest',
    addDepart: '/adddepart',
    updateDepart: '/updatedepart',
    colisByUser: '/colisbyuser',
    createColis: '/createcolis_v2',
    bagageByUser: '/bagagebyuser',
    createBagage: '/createbagage',
    ticketByUser: '/ticketbyuser',
    loadDest: '/loaddest',
    addDestination: '/adddestination',
    destinations: '/destinations',
    itineraries: '/itineraries',
    departures: '/departures',
    displaySiege: '/displaysiege',
    sellBillet: '/sellbillet',
    dashboard: '/dashboard',
  },
  timeout: 30000, // 30 seconds
};